version: 2

defaults: &defaults
  docker:
    -
      image: docker:18.05.0-ce-git
  working_directory: ~/repo
  steps:
    - checkout
    - setup_remote_docker
    -
      run:
        name: Build application Docker image
        command: |
          docker build --tag composer:$VERSION ./$VERSION
    -
      run:
        name: List created images
        command: |
          docker images

jobs:
  build-1.6:
    environment:
      VERSION: "1.6"
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - build-1.6
